---

root: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 6
  sourceType: 'module'

env:
  es6: true
  browser: true
  node: true

rules:
  indent: [2, 2]
  quotes: [2, 'single']
  linebreak-style: [2, 'unix']
  semi: [2, 'never']
